name: amoledx_starter
description: AMOLEDX wallpaper starter app
version: 0.1.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  flutter_wallpaper_manager: ^0.0.4
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^5.15.0
  firebase_storage: ^11.6.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.3
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
